
/*
 * PLEASE DON'T EDIT
 *
 * This file was automatically generated by
 * ./cpu/stm32/dist/irqs/gen_irqs.py
 */

#ifndef IRQS_F3_H
#define IRQS_F3_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined(STM32F302xC)
#define CPU_IRQ_NUMOF                   (82U)
#elif defined(STM32F358xx)
#define CPU_IRQ_NUMOF                   (82U)
#elif defined(STM32F398xx)
#define CPU_IRQ_NUMOF                   (85U)
#elif defined(STM32F302xE)
#define CPU_IRQ_NUMOF                   (85U)
#elif defined(STM32F318xx)
#define CPU_IRQ_NUMOF                   (82U)
#elif defined(STM32F373xC)
#define CPU_IRQ_NUMOF                   (82U)
#elif defined(STM32F328xx)
#define CPU_IRQ_NUMOF                   (82U)
#elif defined(STM32F378xx)
#define CPU_IRQ_NUMOF                   (82U)
#elif defined(STM32F301x8)
#define CPU_IRQ_NUMOF                   (82U)
#elif defined(STM32F334x8)
#define CPU_IRQ_NUMOF                   (82U)
#elif defined(STM32F303xE)
#define CPU_IRQ_NUMOF                   (85U)
#elif defined(STM32F303xC)
#define CPU_IRQ_NUMOF                   (82U)
#elif defined(STM32F303x8)
#define CPU_IRQ_NUMOF                   (82U)
#elif defined(STM32F302x8)
#define CPU_IRQ_NUMOF                   (82U)
#endif

#ifdef __cplusplus
}
#endif

#endif /* IRQS_F3_IRQ_H */
