manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: libresolar
      url-base: https://github.com/LibreSolar
  projects:
    - name: zephyr
      remote: libresolar
      revision: v2.6-branch
      # path must be something else than zephyr as we get a Kconfig include recursion otherwise
      path: rtos
      import:
        # main zephyr modules should be placed in here into zephyr subdirectory
        path-prefix: zephyr
        # only get modules we actually need
        name-whitelist:
          - cmsis
          - edtt
          - hal_stm32
    - name: thingset-device-library
      remote: libresolar
      revision: 0e695f719bb8cf10de212b2b9f41fba65d9327df
      path: zephyr/modules/thingset
