name: Documentation

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0      # necessary to get tags

      - name: Install dependencies
        run: |
          sudo apt install -y git make python3 python3-pip doxygen graphviz
          pip3 install -r docs/requirements.txt

      - name: Build documentation
        run: |
          cd docs
          make html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html/
          enable_jekyll: false
          allow_empty_commit: false
          force_orphan: true
          publish_branch: gh-pages
