name: Build with Zephyr toolchain

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:v0.21.0
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: charge-controller-firmware

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Initialize
        working-directory: charge-controller-firmware
        run: |
          pip3 install -U west
          west init -l .
          west update --narrow
          pip3 install -r ../zephyr/scripts/requirements-base.txt

      - name: Trailing whitespace check
        working-directory: charge-controller-firmware
        run: |
          git diff --check `git rev-list --max-parents=0 HEAD`..HEAD

      - name: Build firmware
        working-directory: charge-controller-firmware
        run: |
          cd app
          west build -b mppt_2420_hc@0.2 -p
          west build -b mppt_2420_lc -p
          west build -b mppt_1210_hus@0.7 -p
          west build -b pwm_2420_lus@0.3 -p

      - name: Run unit-tests
        working-directory: charge-controller-firmware
        run: |
          cd tests
          west build -b native_posix -t run
