//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char arrow_right [] = {
0x41, 0x63, 0x36, 0x1C, 
};
